### PR TITLE
Add AppVeyor CI & fix Windows/MSVC issues

### PR DESCRIPTION
**Pull request by letmaik**
Remaining item from #588. See an example build: https://ci.appveyor.com/project/letmaik/lensfun/builds/27761056

I decided to support Visual Studio versions from 2015 upwards in CI, mostly because that's what I need for my Python wrapper (lensfunpy) to support Python 3.5 upwards.

There were some minor compilation issues that I fixed along the way. Also, some minor cleanup/improvements in the CMake files.

Before this PR is merged, someone has to enable AppVeyor for this repo.

### CODE REVIEW

**Comment by seebk** [comment]
Thanks a lot, in particular for the many fixes of warnings and cleanups!

**Comment by letmaik** [comment]
Thanks for merging. The link in the README (on the badge) to appveyor is broken though.

**Comment by seebk** [comment]
Ok, the link is fixed now.

**Comment by dg0yt** [comment]
This PR is four years old, but the Windows fixes to `apps` are not found in the current release.

**Pull request merged**
