### PR TITLE
Add calibration data for the RF 100-500mm F4.5-7.1 L IS USM

### PR DESCRIPTION
**Pull request by piratenpanda**
and minor distortion update for the RF 85 1.2

### CODE REVIEW

**Comment by piratenpanda** [comment]
I'll modify this PR once https://github.com/lensfun/lensfun/pull/1442 is merged

**Comment by piratenpanda** [comment]
Removed aliases here as well @gnl21

**Comment by gnl21** [comment]
Thanks. It looks like you were the original committer of the data for the 85mm as well (?), so this looks good to go. I don't think this will conflict with #1442, so I'll merge this once the autobuilds have passed.

**Comment by piratenpanda** [comment]
Yes, the 85 is from me

**Comment by gnl21** [comment]
I'm pretty sure that the autobuilds won't work, and then I'll decide that it's not the fault of this change and merge it anyway, so it feels a bit daft to wait, but you never know if something unexpected will show up, so I'm inclined to wait anyway. Do shout if you want it merged now, but otherwise I'll do it if there's nothing odd when the autobuilds come in.

**Comment by piratenpanda** [comment]
I am in no hurry. I have the changes locally. Merge when you feel it's fine. Thank you :)

**Comment by sarunasb** [comment]
> I'm pretty sure that the autobuilds won't work, 

IMO it may be worth waiting for the first (CMake) tests to pass, as they also check database integrity. So if there are issues with XML, those will be indicated.

**Comment by gnl21** [comment]
I had decided to wait for all the autobuilds, and I think that's the right answer really, although I hadn't expected it to take this long. The CMake autobuild already seems to have passed, and the others have made it to the front of the queue.

We'll need to have a look at what's in the AppVeyor autobuild and either get it working or disable it, I think. There's no point in leaving it churning away but expecting it to fail. I know nothing about AppVeyor, but I might be able to start looking at it at the weekend.

**Comment by piratenpanda** [comment]
I'll merge master again when someone merges this

**Comment by gnl21** [comment]
I've been looking at merging this but each time master gets merged to the branch the autobuilds are restarted and I can't see the old results (at least, not from my phone).

I'm happy to merge this now (the autobuilds are showing the pattern I expected), but I'm not clear what you mean about merging master again once this is merged. Is there something that you want to do to this branch, or should I merge it now?

**Comment by piratenpanda** [comment]
There have been commits to master. But maybe I don't need to merge them before. I'm fine with merging now

**Comment by gnl21** [comment]
Yeah, you shouldn't need to merge them into this branch unless there's something that conflicts or something that you think merits retesting the change. Everything else should be dealt with as part of merging this branch into master.

**Pull request merged**
