### PR TITLE
add Fujifilm GFX 50R and distortion for Fujifilm GF 45mm f/2.8 R WR

### PR DESCRIPTION
**Pull request by dllu**
This should address Issue #542

Before: 

pic

After (exported from Darktable):

pic

This lens does not need any TCA correction.

By the way, I am working on a script to automatically correct distortion by extracting horizontal lines. This could make it easier to do distortion correction in the future, instead of laboriously tracing lines in Hugin. Here's a preview:

pic

### CODE REVIEW

**Comment by jas01** [comment]
Can I ask why this pull request are not merge/accepted ? I've got this lenses to and would be happy to help if it's missing anything. Or if «lensfun» think this pull request are not accurate enough.
I also got other GFX lenses and like to know if the community would like to have them in lensfun database

**Comment by dllu** [comment]
No idea why it wasn't merged or accepted. I've been waiting years! It seems lensfun is without any official maintainer so it is all but abandoned. A big shame really.

**Comment by jas01** [comment]
Seem very weird if we looking [https://github.com/lensfun/lensfun/commits/master](commit log)

**Comment by dllu** [comment]
@sboukortt @gnl21 I noticed you two were the most recent to commit to lensfun, could you take a look at this and merge this or provide feedback? thanks!

**Comment by gnl21** [comment]
I'll take a look at it. I'm sorry you've been kept waiting. I'm trying to work through some of the backlog but I don't have much time at the moment and the backlog is large.

Regarding other lenses, I think it would be good to have them in the db. I doubt there will be anyone who can calibrate them for quite a while, but if you can make a PR then I'll try to get them merged.

**Comment by dllu** [comment]
Thanks! I also own the Fujifilm GF 23mm f/4 and the 50mm f/3.5. I'll calibrate those once I feel like it.

**Comment by tuxfanx** [comment]
transferred part of the data to PR #1643 --> close

**Pull request closed without merging**
