### PR TITLE
Normalised model name for Leica DG Nocticron 42.5mm f/1.2

### PR DESCRIPTION
**Pull request by tomalakgeretkal**

### CODE REVIEW

**Comment by sarunasb** [comment]
The change may not be necessary. Is there a RAW sample to check Exif data?

**Comment by tomalakgeretkal** [comment]
Not one that I can share, but here's ExifTool output for it:

```
$ ~/Downloads/Image-ExifTool-12.40/exiftool leica-test.rw2 -G | grep Lens
[PanasonicRaw]  Lens Attached                   : Yes
[PanasonicRaw]  Lens Type Make                  : 2
[PanasonicRaw]  Lens Type Model                 : 21 10
[MakerNotes]    Conversion Lens                 : Off
[MakerNotes]    Lens Serial Number              : 19051500139
[MakerNotes]    Lens Firmware Version           : 0.1.3.0
[Composite]     Lens Type                       : Leica DG Nocticron 42.5mm F1.2 Asph. Power OIS
[Composite]     Lens ID                         : Leica DG Nocticron 42.5mm F1.2 Asph. Power OIS
```

Eliding the "mm" is unusual and breaks lookup for us.

**Comment by tuxfanx** [comment]
[Here is a JPEG sample](https://www.dpreview.com/sample-galleries/2498639999/panasonic-leica-dg-nocticron-42-5mm-f1-2-asph-samples-gallery/1726280343) with exif data. 
```
exiv2 -pv 1726280343.jpeg | grep -i 'model \| lens \| lenstype \| make' 
0x010f Image        Make                        Ascii      10  Panasonic
0x0110 Image        Model                       Ascii       8  DMC-GH3
0x927c Photo        MakerNote                   Undefined 11340  80 97 110 97 115 111 110 105 99 0 0 0 129 0 1 0 3 0 1 0 0 0 7 0 0 0 2 0 7 0 4 0 0 0 0 1 0 0 3 0 3 0  ...
0x0001 MakerNote    Offset                      Long        1  1148
0x0002 MakerNote    ByteOrder                   Ascii       3  II
0x0051 Panasonic    LensType                    Ascii      34  LEICA DG NOCTICRON 42.5/F1.2 
0x8000 Panasonic    MakerNoteVersion            Undefined   4  48 49 52 50

```

**Comment by tomalakgeretkal** [comment]
Alright no problem we'll keep it in our fork. 👍

**Pull request closed without merging**
