### PR TITLE
Adding X100V, XF16-80mm f4

### PR DESCRIPTION
**Pull request by t3mujin**
Cameras
- X100V
- X100F

Lens
- XF16-80mmF4 R OIS WR (tca, vignetting and distortion)
- X100V (tca, vignetting and distortion), and since the x100v has a new lens I created a new lens mount (x100v) for this and upcoming cameras of this family.

### CODE REVIEW

**Comment by t3mujin** [comment]
I'm not really sure why CI is failing, any input?

**Comment by t3mujin** [comment]
@bronger any insights on why it's failing? Don't really know why. Thanks in advance!

**Review by t3mujin — COMMENTED** [review]
Adding some fuji lenses and moving the x100 definition to the right file

**Comment by t3mujin** [comment]
@bronger I got what wasn't working, fixed that and meanwhile added the remaining corrections for x100v, it's ready for merge

**Comment by gnl21** [comment]
Thank you for your contribution and I'm sorry that it has sat for so long.

In trying to clear the backlog I've just merged another PR that adds the X100V but didn't have the lens corrections. If you could rebase/merge that into your branch then I'll merge this. (The PR that I've merged didn't change the lens mount, and I don't *think* it's used for fixed-lens cameras, so it should be fine, but feel free to change it to match the lens data here anyway). If you have a chance to remove the whitespace errors as well then that would be great.

(I might be able to do some or all of this as part of the merge but I'm not totally familiar with GitHub's tools yet, but let me know if you need me to have a go at it!)

**Comment by t3mujin** [comment]
@gnl21 sorry, i've missed this. No prob, i'll merge the changes into mine.

**Comment by pitbuster** [comment]
Is there anything I can do to help get this merged?

**Comment by gnl21** [comment]
Sorry, this was failing the autobuilds, I didn't have time to look into it and then I forgot about it. If we can fix the auto builds then I'll merge this.

**Comment by pitbuster** [comment]
Looking into the CI logs, the errors are
````
    ERROR: Double primary key for cameras!  ('canon', 'canon eos r', None)
    ERROR: Double primary key for cameras!  ('canon', 'canon eos rp', None)
    ERROR: Double primary key for cameras!  ('canon', 'canon eos r5', None)
    ERROR: Double primary key for cameras!  ('canon', 'canon eos r6', None)
````

which is weird, since the changes only touch Fujifilm related files :(

**Comment by gnl21** [comment]
Yes, I saw that. It is weird. My first thought is that it's based on a point where this was already broken in master, so merging the latest master into the branch might fix it. I hope that I can see if this is true tomorrow.

The latest commit seems to have reformatted the whole Fuji file. Could you remove the change to the all the existing entries? Hopefully that's possible in whatever tool you used. (If there's a reason why this version is more correct then it can be fixed in a separate PR)

**Comment by t3mujin** [comment]
@pitbuster @gnl21 yup, I'm quite confused also. I was assuming it was something related with my xml file (not being well formed or failing the dtd/xsd), but I can rollback that commit.

**Comment by t3mujin** [comment]
Both the mil-canon.xml and slr-canon.xml on master contain information for Canon EOS R, maybe that fix should be resolved before merging this one? 

https://raw.githubusercontent.com/lensfun/lensfun/master/data/db/mil-canon.xml
https://raw.githubusercontent.com/lensfun/lensfun/master/data/db/slr-canon.xml

**Comment by gnl21** [comment]
Yes, the duplicate cameras seems to have been the problem. It looks like it was broken in #1422 and there was already a PR reverting the change. I've merged that and so if you update then the autobuilds should work again.

The last commit "Rollback XML format changes" doesn't seem to have undone most of the formatting changes.

**Comment by t3mujin** [comment]
With the work on #1525 this is no longer needed, closing it.

**Pull request closed without merging**
