### PR TITLE
db entries for Canon EOS M6 Mark II and Canon EF-M 32mm f/1.4 STM

### PR DESCRIPTION
**Pull request by douzzer**

### CODE REVIEW

**Comment by tuxfanx** [comment]
Would it be possible to [upload some of your raw images here](https://wilson.bronger.org/calibration)? This makes it easier for us to check your PR. Three of the vignetting images would be enough (open, medium and closed aperture)

**Comment by douzzer** [comment]
Upload done, file "EF-M-32mm-vignetting-samples.tar.gz".

I compared many of my test images with in-camera-corrected JPEGs (factory data), and the `darktable` "lens correction" results with this profile were comparable but better.  Btw, Canon's in-camera vignetting correction has some pretty awful circular artifacts!

I determined the correct distortion correction manually using architectural images, and then cross-checked it with the in-camera correction.  It's an exact match.

The TCA is autogenerated and seems comparable to the in-camera corrections.

It's an awesome lens -- in most uses, the only corrections that are really needed are the vignetting on wide apertures.

**Comment by douzzer** [comment]
I got an auto-email reading, in part,
```
Sorry, we use dcraw and exiv2, and both don’t support CR3 files yet.
```
`dcraw` has broken support for CR3, and `exiv2` has readonly support for CR3 as of version 0.27.5 (what I happen to have installed).

I'm using `darktable` for my post work and the CR3 support there, via libraw, is perfect.

If you need them transcoded just ask.

**Comment by tuxfanx** [comment]
Thanks for the pictures! Everything looks good.

**Pull request merged**
