### PR TITLE
Add LEICA DG 100-400/F4.0-6.3

### PR DESCRIPTION
**Pull request by maxmeyer**
This adds LEICA DG 100-400/F4.0-6.3

### CODE REVIEW

**Comment by maxmeyer** [comment]
Name for the lense was taken from here: https://www.four-thirds.org/en/microft/telephoto.html#i_100-400mm_f040-063_panasonic

**Comment by junkyardsparkle** [comment]
Thanks for the contribution. It looks like there's significant change between 100mm and 200mm. Can you test and confirm that the interpolation produces good results through that range?

For future reference, the "canonical" name source for this purpose would be [here](https://github.com/Exiv2/exiv2/blob/master/src/olympusmn_int.cpp).

**Comment by maxmeyer** [comment]
@junkyardsparkle I'm going to take some pictures again and will verify their results.

**Comment by maxmeyer** [comment]
Name is already fixed.

**Comment by hellbuster** [comment]
What is missing to integrate this? If more testing is needed I can collaborate with that since I own this lens.

**Comment by junkyardsparkle** [comment]
It looks like there have since been some uploads (#889, #966) for this lens. I'll try to make some time for pulling it all together soon.

**Comment by junkyardsparkle** [comment]
I've added the very complete profile provided by #996 to the database. The corrections looked good on the provided images; anyone else who owns this lens can test and report any issues... closing this PR for now.

**Pull request closed without merging**
