### PR TITLE
0.3.3 maintenance release

### PR DESCRIPTION
**Pull request by Sturmflut**
This is a release candidate for a new maintenance release in the 0.3.x branch, as discussed with @seebk . It includes a tool for converting the database (ripped out of the webserver code), an updated ChangeLog and instructions for future releases.

### CODE REVIEW

**Comment by seebk** [comment]
Had a brief check and looks good to me. I have browsed through the commits currently in the [release_0.3.x](https://github.com/Sturmflut/lensfun/tree/release_0.3.x) branch and it seems the few changes in the library code are all already mentioned in the change log. The rest of the commits are only database updates which you have brought up to date with your big commit anyway.

**Review by sarunasb — COMMENTED** [review]
I don't have much to add, but I noticed that some correction additions do not include `<!-- taken with >` comment. Not sure how useful or necessary this is. Perhaps it an be helpful in cases where crop factor questions arise.

Another thing would be failing Appveyor checks. I understand it's build for Windows that fails. Unfortunatley I'm not familiar with Appveyor and haven't compiled a program on Windows since the previous century, so I can hardly help here. But certainly “someone needs to do something” here :)

**Comment by Sturmflut** [comment]
@sarunasb You are right, comments aren't preserved. lxml seems to be able to handle them, I'll look into it.

Another fix: we could remove the broken Sourceforge URL from `lensfun-update-data`.

I was planning to look into AppVeyor. Looks like some file included at the beginning that's not part of lensfun causes the failure.

What do you think about releasing 0.3.3 today, on 22.02.2022? Such a date will not come up again for a very long time :)

**Comment by sarunasb** [comment]
Sounds good to me.

**Comment by Sturmflut** [comment]
@sarunasb It looks like most comments are actually preserved. I'd have to look into why some aren't, but I guess it's not critical for this release since the files used for conversion still exist in master anyways and there are clear instructions for how to re-create them.

I was also wrong about the broken URL. Looks like some of my systems had problems resolving Sourceforge servers at some point.

I've updated the database with the most recent snapshot and tested everything. I think from my view this is ready to be merged. Could one of the two maintainers do the honors, or should I? :)

**Comment by sarunasb** [comment]
Yes, please do the merge.

**Comment by Sturmflut** [comment]
@sarunasb @seebk ..and it's out :) If one of you gives me access to the lensfun.github.io project, I'll update the lens list for this release and add a news item on the front page.

**Comment by sarunasb** [comment]
> @sarunasb @seebk ..and it's out :) If one of you gives me access to the lensfun.github.io project, 
If I can do that, that option must be buried somewhere deeply in Github...

**Comment by sarunasb** [comment]
It looks like a new team can be created with Write privilege to ensfun/lensfun.github.io, correct @seebk ? Don't know if there are other/better ways.

**Comment by seebk** [comment]
Sure, that makes sense. I have added a new @lensfun/website team. @Sturmflut you should now be able to push to the website repo.

**Pull request merged**
