### PR TITLE
Update run apt update before installing libxml2

### PR DESCRIPTION
**Pull request by payano**
apt can't find libxml2-utils

### CODE REVIEW

**Comment by payano** [comment]
Lets see if this works... Otherwise we need to change ubuntu to not the latest version I suppose.

**Comment by payano** [comment]
I think this new cmake.yml also builds PR's.

**Comment by payano** [comment]
Run sudo apt-get install libxml2-utils
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  libxml2-utils
0 upgraded, 1 newly installed, 0 to remove and 17 not upgraded.
Need to get 37.1 kB of archives.
After this operation, 194 kB of additional disk space will be used.
Ign:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libxml2-utils amd64 2.9.10+dfsg-5ubuntu0.20.04.1
Err:1 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libxml2-utils amd64 2.9.10+dfsg-5ubuntu0.20.04.1
  404  Not Found [IP: 20.106.104.242 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2-utils_2.9.10+dfsg-5ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 20.106.104.242 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.

**Comment by tuxfanx** [comment]
...works, thanks!

**Pull request merged**
