### PR TITLE
Remove Travis CI from readme.md

### PR DESCRIPTION
**Pull request by payano**
Travis CI is not in use anymore.

### CODE REVIEW

**Comment by payano** [comment]
Isn't it good to have Travis CI which builds the library for Linux? I thought that Appveyor builds the window version?

**Comment by gnl21** [comment]
Looking at the logs from the build on this change, I would say that yes, AppVeyor is only building on windows.

I would also say that yes, it's a good idea to have some build running on linux. I don't know anything about CI tools that integrate with GitHub and I don't know why the old Travis CI thing got turned off. If we can start it running again then that would be great, but otherwise I guess I'll merge this PR.

**Comment by payano** [comment]
I think we can remove Travis ci and then use the github build system to build the linux library, I'll try to fix the configuration ASAP.

**Comment by seebk** [comment]
Thanks! It seems Travis now has limited ressources for free users and we exceeded our credits. Agree we shoul dmove to Github Actions.

**Pull request merged**
