### PR TITLE
calibration_webserver: CR3 support

### PR DESCRIPTION
**Pull request by jonas-ott**
fixes https://github.com/lensfun/lensfun/issues/2039 by using dcraw_emu from [LibRaw](https://github.com/LibRaw/LibRaw) and removing  the error handling.

I did not test the changes! 
@bronger Because it's your server, could you check if it works?

### CODE REVIEW

**Comment by sarunasb** [comment]
Tested on a fresh calibratio_webserver install. Uploads work for CR3 files. There is new prerequisite to install `libraw-bin` for `dcraw_emu`.

**Comment by sarunasb** [comment]
@bronger 1) any chance to update calibration upload service on `wilson` with the updated source?
2) any chance to upgrade ownCloud (desktop clients won't conenct anymore — server is too old)?

**Comment by bronger** [comment]
I will look into it soon.

**Comment by bronger** [comment]
I updated the calibration webserver, too. Please try a lucky shot by uploading a CR3 and report back.

**Pull request merged**
