### PR TITLE
Add Panasonic LEICA DG 8-18/F2.8-4.0

### PR DESCRIPTION
**Pull request by maxmeyer**
* [x] Verified with calibration images
* [x] Verified with test images

### CODE REVIEW

**Comment by d4rkd3v1l** [comment]
When will this be merged? Really looking forward to have my new favourite lens supported here and hopefully soon after in darktable :-)

**Comment by maxmeyer** [comment]
@d4rkd3v1l In the meantime you can try to create a file at `~/.local/share/lensfun/lensfun.xml` with the given corrections. This also works with darktable+lensfun.

http://lensfun.sourceforge.net/manual/dbsearch.html

**Comment by d4rkd3v1l** [comment]
@maxmeyer Thanks for that hint. Unfortunately I didn't get it working. I really just need to put the file to this location, nothing else?

I put just the new part there, the whole files content, checked the access rights, etc. :-/

**Comment by sarunasb** [comment]
On 06/09/2018 04:41 AM, Martin Straub wrote:
> @maxmeyer <https://github.com/maxmeyer> Thanks for that hint.
> Unfortunately I didn't get it working. I really just need to put the
> file to this location, nothing else?
> 
> I put just the new part there, the whole files content, checked the
> access rights, etc. :-/

Your file needs to be:

<lensdatabase>
  <lens>
  ....correction parameters...
  </lens>
</lensdatabase>

Like the one attached.

-- 
Šarūnas Burdulis
math.dartmouth.edu/~sarunas

**Comment by d4rkd3v1l** [comment]
Thanks guys, finally got it working. But had to put the correction in the darktable.app itself (which for sure is not the preferred place...) but for me it seems like darktable isn't looking for those files at that other places (at least in the mac version).

**Comment by maxmeyer** [comment]
@sarunasb Is there anything missing in this PR to get it merged?

**Comment by sarunasb** [comment]
I would add

<model lang="en">Leica DG Vario-Elmarit 8-18mm f/2.8-4 Asph.</model>

Šarūnas Burdulis
math.dartmouth.edu/~sarunas

**Comment by maxmeyer** [comment]
@sarunasb Done.

**Comment by maxmeyer** [comment]
Thanks.

**Pull request merged**
