### PR TITLE
updated Sigma 35mm f/1.4 DG HSM (A12)

### PR DESCRIPTION
**Pull request by MStraeten**
new measure for near and infinity focus

### CODE REVIEW

**Comment by matt-maguire** [comment]
Was there any issue with the existing measurements?

**Comment by MStraeten** [comment]
I found quite different behavior with near and far focussing distances at least with my lens - so the correction for the far distance was too much on near distances resulting in edges being brighter than the center. So I did a measure for min and max focussing distance - so at least it’s possible to adjust the correction by changing the focal length parameter (at least with darktable)
But Maybe there’re differences between lenses ...

**Comment by matt-maguire** [comment]
Ok, thanks for the update.

**Comment by junkyardsparkle** [comment]
> But Maybe there’re differences between lenses ...

This is very normal, and is probably an issue with any profile which only provides vignetting corrections at infinity (which includes many of the profiles in the database)... unfortunately.

**Comment by davidlbit** [comment]
@MStraeten Has this lens been removed from the Lensfun database? I just updated the database, and also checked the supported lenses on the website, but seems like I couldn't find it.

**Comment by MStraeten** [comment]
it’s there in slr-sigma.xml   <model>Sigma 35mm f/1.4 DG HSM</model>
don’t rely too much those supported lenses lists - they’re often not properly maintained. Check the db instead - if it’s there, it’s not removed ;)
If you don’t see it in darktable then have a look at https://github.com/darktable-org/darktable/wiki/User's-portal#my-lens-is-wrongly-identified

**Comment by davidlbit** [comment]
Okay, I checked again and found out that the lens is not available for any of the sony alpha cameras (I'm owning a Sony A7R iii myself). But I can see that it's in fact available for the canon mirrorless lineup. I assume that means that I need to follow the tutorial to generate a calibration xml file and then send it in via the mailing list?

**Comment by MStraeten** [comment]
if you’re using the canon version of the lens via adapter the definition should match. Otherwise you need to do the measurement for your version

**Pull request merged**
