### PR TITLE
Add Voigtländer 25mm f/0.95 Lens

### PR DESCRIPTION
**Pull request by antonmosich**
This PR adds the Voigtländer Nokton 25mm f/0.95 MFT Lens to the Database.

### CODE REVIEW

**Comment by tuxfanx** [comment]
Would it be possible for you to [upload some raw images](https://wilson.bronger.org/calibration) of the calibration here? That would make it easier for us to check your PR. 
Is it a non-CPU lens (no automatic detection)?

**Comment by antonmosich** [comment]
It is a non-CPU lens. I manually added the EXIF tags needed for the [lens_calibration.py](https://gitlab.com/cryptomilk/lens_calibrate) script to work. When I upload my RAW images, should I use the edited ones, or the original completely unedited RAW files?

**Comment by tuxfanx** [comment]
The raw images as they came out of the camera should be ok - thank's

**Comment by antonmosich** [comment]
Uploaded the RAW files. See #1704

**Comment by tuxfanx** [comment]
Your calibration is ok but there is an error in the build process with your PR. I'm not very familiar with github and programming and therefore I will not merge it.
I can close the PR and you create it again or I create a new one.
In case of a new PR we could shorten the model name. So it would be easier to make entries in cameras and there would be no problems with the umlaut "ä". My proposition:
[NoktonII.zip](https://github.com/lensfun/lensfun/files/8209579/NoktonII.zip)

**Pull request merged**
