### PR TITLE
Add Tamron 150-600 G2

### LINKED ISSUE #1332: Profiles for Tamron 150-600 mm G2 and 15-30 mm G2
Here are two lens profiles I created using Torsten Bronger's calibrate.py (and, in case of the 15-30 mm, hand-tuning of the cromatic aberration parameters in darktable). I hope this is the right way to provide them for inclusion in lensfun.

```
<lens>
    <maker>Tamron</maker>
    <!-- The official name of the lens -->
    <model>Tamron SP AF 150-600mm F/5-6.3 Di VC USD G2</model>
    <!-- The 'LensIDNumber' EXIF tag - use with old versions of exiv2 -->
    <!-- <model>227</model> -->
    <mount>Nikon F AF</mount>
    <cropfactor>1</cropfactor>
    <calibration>
        <distortion model="ptlens" focal="150" a="-0.009" b="0.044" c="-0.046"/>
        <distortion model="ptlens" focal="210" a="0.011" b="-0.03" c="0.038"/>
        <distortion model="ptlens" focal="250" a="-0.007" b="0.042" c="-0"/>
        <distortion model="ptlens" focal="300" a="-0.007" b="0.014" c="-0.056"/>
        <distortion model="ptlens" focal="350" a="0.007" b="-0.013" c="0.01"/>
        <distortion model="ptlens" focal="550" a="0.005" b="-0.016" c="0.033"/>
        <distortion model="ptlens" focal="600" a="0.005" b="-0.015" c="0.028"/>
        <tca model="poly3" focal="150" vr="1.0001529" vb="1.0000197"/>
        <tca model="poly3" focal="210" vr="1.0000699" vb="1.0000183"/>
        <tca model="poly3" focal="250" vr="0.9999986" vb="1.0000267"/>
        <tca model="poly3" focal="300" vr="0.9999165" vb="1.0000426"/>
        <tca model="poly3" focal="350" vr="0.9998567" vb="1.0000432"/>
        <tca model="poly3" focal="550" vr="0.9998065" vb="0.9999550"/>
        <tca model="poly3" focal="600" vr="0.9997072" vb="0.9999799"/>
        <vignetting model="pa" focal="150" aperture="5" distance="10" k1="-0.7906" k2="0.3710" k3="-0.0872"/>
        <vignetting model="pa" focal="150" aperture="5" distance="1000" k1="-0.7906" k2="0.3710" k3="-0.0872"/>
        <vignetting model="pa" focal="150" aperture="7.1" distance="10" k1="-0.1130" k2="0.0234" k3="-0.1039"/>
        <vignetting model="pa" focal="150" aperture="7.1" distance="1000" k1="-0.1130" k2="0.0234" k3="-0.1039"/>
        <vignetting model="pa" focal="150" aperture="10" distance="10" k1="-0.1079" k2="-0.0637" k3="0.0570"/>
        <vignetting model="pa" focal="150" aperture="10" distance="1000" k1="-0.1079" k2="-0.0637" k3="0.0570"/>
        <vignetting model="pa" focal="150" aperture="13" distance="10" k1="-0.1102" k2="-0.0603" k3="0.0552"/>
        <vignetting model="pa" focal="150" aperture="13" distance="1000" k1="-0.1102" k2="-0.0603" k3="0.0552"/>
        <vignetting model="pa" focal="150" aperture="32" distance="10" k1="-0.1174" k2="-0.0430" k3="0.0426"/>
        <vignetting model="pa" focal="150" aperture="32" distance="1000" k1="-0.1174" k2="-0.0430" k3="0.0426"/>
        <vignetting model="pa" focal="250" aperture="5.6" distance="10" k1="-0.5150" k2="0.2326" k3="-0.1321"/>
        <vignetting model="pa" focal="250" aperture="5.6" distance="1000" k1="-0.5150" k2="0.2326" k3="-0.1321"/>
        <vignetting model="pa" focal="250" aperture="8" distance="10" k1="-0.1402" k2="0.1961" k3="-0.2036"/>
        <vignetting model="pa" focal="250" aperture="8" distance="1000" k1="-0.1402" k2="0.1961" k3="-0.2036"/>
        <vignetting model="pa" focal="250" aperture="11" distance="10" k1="-0.0928" k2="-0.0290" k3="0.0312"/>
        <vignetting model="pa" focal="250" aperture="11" distance="1000" k1="-0.0928" k2="-0.0290" k3="0.0312"/>
        <vignetting model="pa" focal="250" aperture="14" distance="10" k1="-0.0943" k2="-0.0283" k3="0.0315"/>
        <vignetting model="pa" focal="250" aperture="14" distance="1000" k1="-0.0943" k2="-0.0283" k3="0.0315"/>
        <vignetting model="pa" focal="250" aperture="36" distance="10" k1="-0.0959" k2="-0.0254" k3="0.0288"/>
        <vignetting model="pa" focal="250" aperture="36" distance="1000" k1="-0.0959" k2="-0.0254" k3="0.0288"/>
        <vignetting model="pa" focal="340" aperture="6" distance="10" k1="-0.2656" k2="-0.5242" k3="0.3357"/>
        <vignetting model="pa" focal="340" aperture="6" distance="1000" k1="-0.2656" k2="-0.5242" k3="0.3357"/>
        <vignetting model="pa" focal="340" aperture="9" distance="10" k1="-0.0654" k2="0.0614" k3="-0.2246"/>
        <vignetting model="pa" focal="340" aperture="9" distance="1000" k1="-0.0654" k2="0.0614" k3="-0.2246"/>
        <vignetting model="pa" focal="340" aperture="13" distance="10" k1="-0.1248" k2="0.1490" k3="-0.1313"/>
        <vignetting model="pa" focal="340" aperture="13" distance="1000" k1="-0.1248" k2="0.1490" k3="-0.1313"/>
        <vignetting model="pa" focal="340" aperture="16" distance="10" k1="-0.0839" k2="-0.0151" k3="0.0194"/>
        <vignetting model="pa" focal="340" aperture="16" distance="1000" k1="-0.0839" k2="-0.0151" k3="0.0194"/>
        <vignetting model="pa" focal="340" aperture="38" distance="10" k1="-0.0847" k2="-0.0157" k3="0.0201"/>
        <vignetting model="pa" focal="340" aperture="38" distance="1000" k1="-0.0847" k2="-0.0157" k3="0.0201"/>
        <vignetting model="pa" focal="460" aperture="6.3" distance="10" k1="-0.4978" k2="-0.3285" k3="0.3336"/>
        <vignetting model="pa" focal="460" aperture="6.3" distance="1000" k1="-0.4978" k2="-0.3285" k3="0.3336"/>
        <vignetting model="pa" focal="460" aperture="9" distance="10" k1="0.1619" k2="-0.8998" k3="0.4403"/>
        <vignetting model="pa" focal="460" aperture="9" distance="1000" k1="0.1619" k2="-0.8998" k3="0.4403"/>
        <vignetting model="pa" focal="460" aperture="13" distance="10" k1="-0.1188" k2="0.2383" k3="-0.2974"/>
        <vignetting model="pa" focal="460" aperture="13" distance="1000" k1="-0.1188" k2="0.2383" k3="-0.2974"/>
        <vignetting model="pa" focal="460" aperture="18" distance="10" k1="-0.0818" k2="0.0124" k3="-0.0071"/>
        <vignetting model="pa" focal="460" aperture="18" distance="1000" k1="-0.0818" k2="0.0124" k3="-0.0071"/>
        <vignetting model="pa" focal="460" aperture="40" distance="10" k1="-0.0736" k2="-0.0200" k3="0.0207"/>
        <vignetting model="pa" focal="460" aperture="40" distance="1000" k1="-0.0736" k2="-0.0200" k3="0.0207"/>
        <vignetting model="pa" focal="600" aperture="6.3" distance="10" k1="-0.9914" k2="0.8181" k3="-0.3364"/>
        <vignetting model="pa" focal="600" aperture="6.3" distance="1000" k1="-0.9914" k2="0.8181" k3="-0.3364"/>
        <vignetting model="pa" focal="600" aperture="9" distance="10" k1="0.0588" k2="-0.9447" k3="0.5775"/>
        <vignetting model="pa" focal="600" aperture="9" distance="1000" k1="0.0588" k2="-0.9447" k3="0.5775"/>
        <vignetting model="pa" focal="600" aperture="13" distance="10" k1="-0.0355" k2="-0.0262" k3="-0.1237"/>
        <vignetting model="pa" focal="600" aperture="13" distance="1000" k1="-0.0355" k2="-0.0262" k3="-0.1237"/>
        <vignetting model="pa" focal="600" aperture="18" distance="10" k1="-0.0741" k2="0.0094" k3="-0.0064"/>
        <vignetting model="pa" focal="600" aperture="18" distance="1000" k1="-0.0741" k2="0.0094" k3="-0.0064"/>
        <vignetting model="pa" focal="600" aperture="40" distance="10" k1="-0.0659" k2="-0.0233" k3="0.0210"/>
        <vignetting model="pa" focal="600" aperture="40" distance="1000" k1="-0.0659" k2="-0.0233" k3="0.0210"/>
    </calibration>
</lens>
```

```
<lens>
    <maker>Tamron</maker>
    <!---The actual name--->
    <model>SP 15-30mm f/2.8 Di VC USD G2</model>
    <!---The lens ID--->
    <!---<model>202</model>--->
    <mount>Nikon F AF</mount>
    <cropfactor>1</cropfactor>
    <calibration>
        <distortion model="ptlens" focal="15" a="0.00212" b="-0.03159" c="0.03764"/>
        <distortion model="ptlens" focal="18" a="-0.0008" b="-0.00486" c="0.00566"/>
        <distortion model="ptlens" focal="20" a="-0.00395" b="0.01511" c="-0.01731"/>
        <distortion model="ptlens" focal="24" a="-0.00042" b="0.0104" c="-0.00908"/>
        <distortion model="ptlens" focal="30" a="0.00574" b="-0.00861" c="0.0108"/>
        <tca model="poly3" focal="15" vr="1.00031" vb="1.00015"/>
        <tca model="poly3" focal="18" vr="1.00030" vb="1.00017"/>
        <tca model="poly3" focal="20" vr="1.00019" vb="1.00024"/>
        <tca model="poly3" focal="24" vr="1.00013" vb="1.00019"/>
        <tca model="poly3" focal="30" vr="1.00012" vb="1.00011"/>
        <vignetting model="pa" focal="15" aperture="2.8" distance="10" k1="-0.5434" k2="-0.4103" k3="0.2630"/>
        <vignetting model="pa" focal="15" aperture="2.8" distance="1000" k1="-0.5434" k2="-0.4103" k3="0.2630"/>
        <vignetting model="pa" focal="15" aperture="4" distance="10" k1="-0.6211" k2="0.7153" k3="-0.6347"/>
        <vignetting model="pa" focal="15" aperture="4" distance="1000" k1="-0.6211" k2="0.7153" k3="-0.6347"/>
        <vignetting model="pa" focal="15" aperture="5.6" distance="10" k1="-0.5277" k2="0.3295" k3="-0.1830"/>
        <vignetting model="pa" focal="15" aperture="5.6" distance="1000" k1="-0.5277" k2="0.3295" k3="-0.1830"/>
        <vignetting model="pa" focal="15" aperture="8" distance="10" k1="-0.6143" k2="0.4141" k3="-0.1706"/>
        <vignetting model="pa" focal="15" aperture="8" distance="1000" k1="-0.6143" k2="0.4141" k3="-0.1706"/>
        <vignetting model="pa" focal="15" aperture="11" distance="10" k1="-0.4979" k2="0.1889" k3="-0.0485"/>
        <vignetting model="pa" focal="15" aperture="11" distance="1000" k1="-0.4979" k2="0.1889" k3="-0.0485"/>
        <vignetting model="pa" focal="15" aperture="22" distance="10" k1="-0.4140" k2="0.0203" k3="0.0425"/>
        <vignetting model="pa" focal="15" aperture="22" distance="1000" k1="-0.4140" k2="0.0203" k3="0.0425"/>
        <vignetting model="pa" focal="18" aperture="2.8" distance="10" k1="-0.4827" k2="-0.6507" k3="0.5390"/>
        <vignetting model="pa" focal="18" aperture="2.8" distance="1000" k1="-0.4827" k2="-0.6507" k3="0.5390"/>
        <vignetting model="pa" focal="18" aperture="4" distance="10" k1="-0.4889" k2="0.2100" k3="-0.1414"/>
        <vignetting model="pa" focal="18" aperture="4" distance="1000" k1="-0.4889" k2="0.2100" k3="-0.1414"/>
        <vignetting model="pa" focal="18" aperture="5.6" distance="10" k1="-0.4763" k2="0.1612" k3="-0.0190"/>
        <vignetting model="pa" focal="18" aperture="5.6" distance="1000" k1="-0.4763" k2="0.1612" k3="-0.0190"/>
        <vignetting model="pa" focal="18" aperture="8" distance="10" k1="-0.4610" k2="0.1358" k3="-0.0061"/>
        <vignetting model="pa" focal="18" aperture="8" distance="1000" k1="-0.4610" k2="0.1358" k3="-0.0061"/>
        <vignetting model="pa" focal="18" aperture="11" distance="10" k1="-0.4240" k2="0.0711" k3="0.0258"/>
        <vignetting model="pa" focal="18" aperture="11" distance="1000" k1="-0.4240" k2="0.0711" k3="0.0258"/>
        <vignetting model="pa" focal="18" aperture="22" distance="10" k1="-0.2981" k2="-0.1746" k3="0.1605"/>
        <vignetting model="pa" focal="18" aperture="22" distance="1000" k1="-0.2981" k2="-0.1746" k3="0.1605"/>
        <vignetting model="pa" focal="20" aperture="2.8" distance="10" k1="-0.5353" k2="-0.5515" k3="0.5054"/>
        <vignetting model="pa" focal="20" aperture="2.8" distance="1000" k1="-0.5353" k2="-0.5515" k3="0.5054"/>
        <vignetting model="pa" focal="20" aperture="4" distance="10" k1="-0.4066" k2="0.0174" k3="-0.0111"/>
        <vignetting model="pa" focal="20" aperture="4" distance="1000" k1="-0.4066" k2="0.0174" k3="-0.0111"/>
        <vignetting model="pa" focal="20" aperture="5.6" distance="10" k1="-0.4603" k2="0.1323" k3="0.0049"/>
        <vignetting model="pa" focal="20" aperture="5.6" distance="1000" k1="-0.4603" k2="0.1323" k3="0.0049"/>
        <vignetting model="pa" focal="20" aperture="8" distance="10" k1="-0.3823" k2="-0.0124" k3="0.0837"/>
        <vignetting model="pa" focal="20" aperture="8" distance="1000" k1="-0.3823" k2="-0.0124" k3="0.0837"/>
        <vignetting model="pa" focal="20" aperture="11" distance="10" k1="-0.1130" k2="-0.5119" k3="0.3494"/>
        <vignetting model="pa" focal="20" aperture="11" distance="1000" k1="-0.1130" k2="-0.5119" k3="0.3494"/>
        <vignetting model="pa" focal="20" aperture="22" distance="10" k1="-0.4026" k2="0.0160" k3="0.0669"/>
        <vignetting model="pa" focal="20" aperture="22" distance="1000" k1="-0.4026" k2="0.0160" k3="0.0669"/>
        <vignetting model="pa" focal="24" aperture="2.8" distance="10" k1="-0.8167" k2="0.0216" k3="0.2059"/>
        <vignetting model="pa" focal="24" aperture="2.8" distance="1000" k1="-0.8167" k2="0.0216" k3="0.2059"/>
        <vignetting model="pa" focal="24" aperture="4" distance="10" k1="-0.1416" k2="-0.5481" k3="0.3153"/>
        <vignetting model="pa" focal="24" aperture="4" distance="1000" k1="-0.1416" k2="-0.5481" k3="0.3153"/>
        <vignetting model="pa" focal="24" aperture="5.6" distance="10" k1="-0.3630" k2="-0.0277" k3="0.0821"/>
        <vignetting model="pa" focal="24" aperture="5.6" distance="1000" k1="-0.3630" k2="-0.0277" k3="0.0821"/>
        <vignetting model="pa" focal="24" aperture="8" distance="10" k1="-0.2677" k2="-0.2138" k3="0.1909"/>
        <vignetting model="pa" focal="24" aperture="8" distance="1000" k1="-0.2677" k2="-0.2138" k3="0.1909"/>
        <vignetting model="pa" focal="24" aperture="11" distance="10" k1="-0.0123" k2="-0.6588" k3="0.4174"/>
        <vignetting model="pa" focal="24" aperture="11" distance="1000" k1="-0.0123" k2="-0.6588" k3="0.4174"/>
        <vignetting model="pa" focal="24" aperture="22" distance="10" k1="-0.0258" k2="-0.6401" k3="0.4063"/>
        <vignetting model="pa" focal="24" aperture="22" distance="1000" k1="-0.0258" k2="-0.6401" k3="0.4063"/>
        <vignetting model="pa" focal="30" aperture="2.8" distance="10" k1="-1.0032" k2="0.5757" k3="-0.1432"/>
        <vignetting model="pa" focal="30" aperture="2.8" distance="1000" k1="-1.0032" k2="0.5757" k3="-0.1432"/>
        <vignetting model="pa" focal="30" aperture="4" distance="10" k1="-0.2193" k2="-0.4462" k3="0.2784"/>
        <vignetting model="pa" focal="30" aperture="4" distance="1000" k1="-0.2193" k2="-0.4462" k3="0.2784"/>
        <vignetting model="pa" focal="30" aperture="5.6" distance="10" k1="-0.3219" k2="0.0066" k3="0.0081"/>
        <vignetting model="pa" focal="30" aperture="5.6" distance="1000" k1="-0.3219" k2="0.0066" k3="0.0081"/>
        <vignetting model="pa" focal="30" aperture="8" distance="10" k1="-0.1213" k2="-0.4224" k3="0.2841"/>
        <vignetting model="pa" focal="30" aperture="8" distance="1000" k1="-0.1213" k2="-0.4224" k3="0.2841"/>
        <vignetting model="pa" focal="30" aperture="11" distance="10" k1="-0.1871" k2="-0.3022" k3="0.2185"/>
        <vignetting model="pa" focal="30" aperture="11" distance="1000" k1="-0.1871" k2="-0.3022" k3="0.2185"/>
        <vignetting model="pa" focal="30" aperture="22" distance="10" k1="-0.2210" k2="-0.2393" k3="0.1822"/>
        <vignetting model="pa" focal="30" aperture="22" distance="1000" k1="-0.2210" k2="-0.2393" k3="0.1822"/>
    </calibration>
</lens>
```

### LINKED ISSUE #1382: Add "Tamron SP AF 150-600mm F/5-6.3 Di VC USD G2" to slr-tamron.xml
Please add the attached lens data to the lensfun data base.
[lensfun.xml.zip](https://github.com/lensfun/lensfun/files/6103601/lensfun.xml.zip)

You can find the raw files and calibration data at issue https://github.com/lensfun/lensfun/issues/1383

### PR DESCRIPTION
**Pull request by gnl21**
Partially resolves #1332
Resolves #1382, #1383

### CODE REVIEW

**Comment by gnl21** [comment]
@mkunzBGC this is what I'm proposing to add to the database.

**Comment by mkunzBGC** [comment]
Hi @gnl21,

I've done a comparison of the parameter set in this PR and the ones I suggested in #1332. For this comparison I used [my calibration data](https://nc.imfus.de/index.php/s/TFaz8jNsQ2Hd6MP). You can find the corrected images [here](https://nc.imfus.de/index.php/s/aZp24j9kMpPMYeC). My observations:

1. Despite the very different distortion parameters, both parameter sets correct distortion well. The differences in the corrected images are restricted to the image centre and I can't decide which one works better. 300 mm are an exception in that the results differ all over the frame, but even there I have a hard time determining which one works better.
2. TCA correction is very similar, maybe the parameters from #1332 work a little bit better (which might be expected as they are derived from the very same images).
3. The vignetting images used for #1332 were taken under grey, open sky with a "milk glass" (actually a plastic film for crafting lamps) in front of the lens, i.e. under optimal conditions as far as I can tell. For large f-numbers, the correction results don't differ a lot (because there is not much vignetting to start with), but for lower f-numbers the parameters from #1332 perform much better than the ones in this PR. Note that I increased the contrast in the corrected images to make differences more visible.

All in all, I have no preference as to which distortion and TCA parameters to include in lensfun. However, I would strongly suggest to use the vignetting parameters from #1332.

**Comment by tuxfanx** [comment]
is it possible to get some raw pictures to check? https://wilson.bronger.org/calibration

**Comment by gnl21** [comment]
I think there are already some raw images in the upload, but until recently I didn't have access to them. I'll sort this one out over the weekend.

**Comment by tuxfanx** [comment]
You are right, there are some in the upload (issue #1383). However, I could only find raw images for vignetting determination. I couldn't find raw images for tca or distortion determination, nor any normal raw images.
A few raw images with which the effect of the calibration data can be checked would be enough.

**Comment by gnl21** [comment]
So, the original problem here was that we had 2 sets of data for this lens and no good way to check the difference because I couldn't get access to the calibration images. (I had no idea it would take so long for me to regain access to then!) The distortion and tca corrections were checked out above as being mostly equivalent, so I'm happy with that.

I originally used this data out of the 2 submissions because the other contained some errors, but since those errors are now fixed and the other data apparently has better vignetting correction, I'm planning to switch this PR to use the other data. If that gives good vignetting correction for the images from the upload (or if there are problems with those images), then I think we have got to the bottom of things and should merge the updated PR.

If it turns out that the uploaded vignetting images are high quality but just give different results then I don't know what the right answer is, but hopefully that won't be a problem.

If you want to repeat some of the tests that were done above then there is a link to the calibration images that correspond to the other set of data for this lens, although after this much time the link may no longer be live)

**Comment by tuxfanx** [comment]
If you now have access to the upload, then you should continue to edit and merge the PR. Then I don't have to check everything again.

**Comment by mkunzBGC** [comment]
> If you want to repeat some of the tests that were done above then there is a link to the calibration images that correspond to the other set of data for this lens, although after this much time the link may no longer be live)
Here is a [new link to the raw images](https://nc.imfus.de/index.php/s/TfRaSjrPr93Ai8z).

**Comment by tuxfanx** [comment]
tested with pictures from mkunzBGC --> calibration works good

**Pull request merged**
