### PR TITLE
Update slr-canon.xml

### PR DESCRIPTION
**Pull request by PeterWem**
Added missing TCA parts for Canon EF 100-200mm f/4.5A

Added: 
Canon EF 24mm f/1.4L II USM
Canon EF 50mm f/1.2L USM
EF300mm f/2.8L IS USM +1.4x extender
EF300mm f/2.8L IS USM +1.4x III extender
EF300mm f/2.8L IS USM +2x III extender

EF500mm f/4L IS USM

### CODE REVIEW

**Comment by piratenpanda** [comment]
I just realized you have the 100-500 here as well. Would you mind comparing to my values from https://github.com/lensfun/lensfun/pull/1551 to decide which we should take

**Comment by PeterWem** [comment]
@piratenpanda The 100-500 is yours. I filled my mil-canon.xml at my homepage with PR and tickets when no PR here at Lensfun were accepted. When I was asked by @Sturmflut to create a new PR your 100-500 was taken from my hompage xml file, because I can't find it in the first PR I created.

I have no idea how to separate lenses and PR here at Github. I just click fetch upstream, I update the mil-canon.xml in my repository and click contribute. My PR is never accepted so it just fills up when I add more lenses.

**Comment by piratenpanda** [comment]
I see, so this is a huge agglomeration of different stuff. I was just confused because the values are different to mine but I now realize it's the old values from the beginning of my PR.

**Comment by piratenpanda** [comment]
I'd recommend keeping a separate repository for each PR and not mixing that with your local installation/changes to keep the PRs clean. This one here can't be merged so I'd recommend starting a new one.

**Pull request closed without merging**
