### PR TITLE
Added support for running calibrate.py on Windows

### PR DESCRIPTION
**Pull request by peci1**
This PR adds support for running calibrate.py on Windows, which I originally offered in https://sourceforge.net/p/lensfun/features/89/#c1d9 .

The PR seems to be quite big, but most of the changes are whitespace changes and moving blocks of code around (which was required to work properly on Windows). So I separated the changes in several commits to allow easier reviewing. The script probably doesn't work on any of the intermediate commits, but it should work on the latest commit. So you might consider squashing this PR after reviewing it.

I haven't tested the script on Linux, so it'd be nice if you'd run at least some basic checks that I haven't broken anything.

### CODE REVIEW

**Comment by junkyardsparkle** [comment]
I've been using this verson on Linux lately with no issues, but it's not my script, so I'll leave the merge up to @bronger.

**Comment by junkyardsparkle** [comment]
Merged. I haven't been able to test on Windows, but the it doesn't break anything and is probably more readable... and will be easier to adapt for anyone wanting to use GraphicsMagick instead of ImageMagick.

**Comment by bronger** [comment]
(Please avoid squashing.)

Commit a41423d seems odd to me – can a `setdefault` result in a `KeyError`?

Apart from that: Thank you for the contribution!

**Comment by peci1** [comment]
@bronger You're right, the try block seems unnecessary. However, it's been a long time since I used the script last, so I don't remember if it was really needed for something or not... Anyways, leaving it there shouldn't harm anything, should it?

**Comment by bronger** [comment]
When reading the source code, it confuses you for a one or two minutes.  Therefore, such locations should be straightened out.

**Comment by aliensojurner** [comment]
@peci1 Are you still around? I've been trying to contact you in regards to the Windows version of the Calibrate.py script. I tried the one from https://github.com/lensfun/lensfun/pull/291 but that failed on Windows. I also edited the script to move the definitions to the top and was able to generate a lenses.txt file but it never generates any TIFFS and the second run always fails. Is there an updated version of calibrate.py for Windows that you can provide me with? I tried reaching out to you via soureforge also. I am in desperate need for a Windows version of this script so we can run it against a large set of files on Windows to generate TCA corrections for a bunch of lenses that are missing this data.

**Comment by peci1** [comment]
Hi @aliensojurner . I haven't used the script for a while but I can help debugging. I just don't have a set of calibration files to use right now, so it'd help if you sent me your files, e.g. over send.firefox.com . Is that possible?

**Comment by aliensojurner** [comment]
Hi @peci1 That would be most helpful. I have included a single RAW file and the partially fixed calibrate.py file. I moved the definitions to the top and got it to half work but as I mentioned it's not generating TIFFs and the second run fails completely. If you could debug this script so it works on Windows I would be most appreciative.  I only need it to work to process the files, I'm able to do the actual distortion corrections myself. 

Here's the link to the RAW file and the calibrate-partially fixed.py file. Thank you again. 
https://send.firefox.com/download/18c52d292cc86770/#Yy5hlk8BrQqUVeTk63ftlw

**Comment by aliensojurner** [comment]
Hi @peci1 is there anything else you may need from me so that you can debug that script?

**Comment by aliensojurner** [comment]
Hi @peci1 Have you had any time to troublshoot this script so I can run this process on Windows?

**Comment by peci1** [comment]
Still waiting for the sample RAW files, since I've already got rid of mine. If you can provide me with a set, I'll have a look at it.

**Comment by aliensojurner** [comment]
I sent them to the link you provided so I thought they made it to you. I've made a new link and uploaded a single RAW file that I was using for debug testing along with the partially fixed calibrate.py file. Sorry you didn't get them originally. 

https://send.firefox.com/download/020ec65a84d73996/#b3z2JlVIqkaK9c-KfHtdhw

**Comment by peci1** [comment]
Ah, I'm sorry, I must have missed the previous post with the sample files. 

I tested the script on the files you sent me and it works fine for me. Both for your `calibrate-partial fixed.py` and for the [current master calibrate.py](https://raw.githubusercontent.com/lensfun/lensfun/master/tools/calibrate/calibrate.py). 

Did you follow [the tutorial](https://wilson.bronger.org/lens_calibration_tutorial/) thoroughly? I.e., do you have the RAW file in a subfolder called `distortion`? And do you have the spelling correct? This is one of the trickier words to spell...

Moreover, I expect that you got all the dependencies installed and set up properly, so the script doesn't yell at you something like 

    The following packages are missing (Ubuntu packages, names may differ on other systems):
    hugin-tools  exiv2
    Abort.

Btw., this is the `lenses.txt` it generated for your sample file:

```
# For suggestions for <maker> and <mount> see
    # <https://github.com/lensfun/lensfun/tree/master/data/db>.
    # <aspect-ratio> is optional and by default 3:2.
    # Omit <type> for rectilinear lenses.
    
35mm F1.4 G: <maker>, <mount>, <cropfactor>, <aspect-ratio>, <type>
distortion(35.0mm) = , , 
```

Until you manually fix the `lenses.txt` after the first run of the script, the calibrate script is expected to fail, as is mentioned on the tutorial.

If you still face some errors, please be more verbose about them and put here every error log the program produces.

**Comment by aliensojurner** [comment]
Well yes and no. I do have all the dependencies installed so it doesn't give the error messages you mentioned, and it does generate a lenses.txt file. However there are a couple of problems here. 
1. On Mac, during the first run before it generates the lenses.txt file it also takes the raw file in the distortion folder and generates a TIFF. On Windows this does not happen. 
2. On the 2nd run that you do once you have edited the lenses.txt file and you also have a file in the "tca" folder, you get several assertions and a failure. It does not generate any of the tca files that are generated on Mac in order to obtain those tca coefficients. 

So yes the script execution works for the first run, but the second run is a tragic failure. Does that make sense?

**Comment by aliensojurner** [comment]
Directory contents
dir contents

Screenshot of the first run
first run

Screenshot and text and assertions from the second run
second run

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files (x86)\Python37-32\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\RobertLounsberry\Desktop\35mm F1.4 G\calibrate-partial fixed.py", line 130, in generate_tca_tiffs
    subprocess.check_call(generate_raw_conversion_call(filename, ["-4", "-o", "0", "-M"]))
  File "C:\Program Files (x86)\Python37-32\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['dcraw', '-T', '-t', '0', '-4', '-o', '0', '-M', 'Dariusz Kowalski - DK_20190518_Full35mmLensCopmarition_00006.arw']' returned non-zero exit status 3221225477.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibrate-partial fixed.py", line 407, in <module>
    for filename, tiff_filename, tca_filename in pool.map(generate_tca_tiffs, raw_files):
  File "C:\Program Files (x86)\Python37-32\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Program Files (x86)\Python37-32\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
subprocess.CalledProcessError: Command '['dcraw', '-T', '-t', '0', '-4', '-o', '0', '-M', 'Dariusz Kowalski - DK_20190518_Full35mmLensCopmarition_00006.arw']' returned non-zero exit status 3221225477.

**Comment by peci1** [comment]
So let's try calling the failed command manually to see what happens:

    dcraw -T -t 0 -4 -o 0 -M 'Dariusz Kowalski - DK_20190518_Full35mmLensCopmarition_00006.arw'

**Comment by aliensojurner** [comment]
When I run that commend I just get no output at all. 
dcraw

**Comment by aliensojurner** [comment]
Any movement on this sir? Do you need more information or need me to try something else?

**Comment by peci1** [comment]
Well, I can't be of any help here. It's definitely a problem with dcraw on your side. I cannot help with that. Until you figure out how to fix it so that the above command generates a TIFF file, you're out of luck with the whole calibrate script.

You can try executing `echo %errorlevel%` to see the exit code of dcraw. You need it to be zero (that means success).

**Comment by aliensojurner** [comment]
Sorry to bother, but how would I add that? Where on the command line or is there a python way I need to add that to try and run it from IDLE?

**Comment by peci1** [comment]
No. You run this in the standard Windows command line (Start->Run->cmd.exe).

**Pull request merged**
