### PR TITLE
Fix checking Windows platform for non-msvc toolchain

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/lensfun/lensfun/issues/1998

### CODE REVIEW

**Comment by newcapricasean** [comment]
I'm relatively new to this github, compiling, and linux... If it's become "commit" ... how long before the actual source code is updated with this change?

**Comment by newcapricasean** [comment]
Modifying the database.cpp and lens.cpp files, with the suggested changes, resolved the issue for me... Thank you!!!

**Comment by ss23** [comment]
@sarunasb Any chance of a merge on this one? It's simple and will mean less issues being opened about building on Windows :)

**Comment by sarunasb** [comment]
Fixed by https://github.com/lensfun/lensfun/commit/6cb00f4445f0a7edaae306bbf4f340de37b58fb8.

**Pull request closed without merging**
