### PR TITLE
Add Fujifilm XF16-80 f/4 R OIS WR from #1059

### PR DESCRIPTION
**Pull request by rrenomeron**
The pictures in #1059 weren't perfect, but after playing around with the Hugin Lens Calibration tool, I got some values that looked pretty good in darktable.

### CODE REVIEW

**Comment by marco44** [comment]
Hi, I've been trying these on one of my pictures that exhibits both TCA and distortion on this lens. Distortion seems good, TCA not so. Here are the pics:
https://marco44.duckdns.org/2020-06-29_06_51_03_XT040112_0-no-corrections.jpg
https://marco44.duckdns.org/2020-06-29_06_51_03_XT040112_0-only-distortion.jpg
https://marco44.duckdns.org/2020-06-29_06_51_03_XT040112_0-all-corrections.jpg
I don't feel the TCA is really an improvement on this picture (taken at 16mm).

**Comment by rrenomeron** [comment]
Thanks for the feedback.

I didn't focus on the TCA too much; the values are whatever the calibrate.py scripts computed, so perhaps the images I used didn't have a lot of TCA on them.  (I am not an expert on the calibration process.)

Unfortunately, I no longer have this lens in my possession, so I'm unable to do better corrections with different images.

**Comment by dbobak** [comment]
Few days ago I uploaded some pictures made with that lens in the #1210
Maybe it will be useful?

**Comment by marco44** [comment]
Couldn't it be merged as is ? It would still be much better than nothing. Or without the TCA ?

**Comment by tuxfanx** [comment]
correction data for distortion and tca are included in the database

**Pull request closed without merging**
