### PR TITLE
Add Panasonic LEICA DG NOCTICRON 42.5/F1.2

### PR DESCRIPTION
**Pull request by maxmeyer**
* [x] Verified with calibration photos
* [x] Verified with test set

### CODE REVIEW

**Comment by maxmeyer** [comment]
@sarunasb Done here as well.

**Comment by sarunasb** [comment]
Request made to use model element for lang="en" as:

Leica DG Nocticron 42.5mm f/1.2 Asph. Power OIS

**Comment by maxmeyer** [comment]
@sarunasb Sorry for that, I oversaw that comma and remove the `Power OIS` before pushing. Where do you get the names from?

I pushed an update.

**Comment by sarunasb** [comment]
On 2018-06-13 14:39, Dennis Günnewig wrote:
> @sarunasb <https://github.com/sarunasb> Sorry for that, I oversaw that
> comma and remove the |Power OIS| before pushing. Where do you get the
> names from?

From manufacturer's and vendors' listings, but also coordinate with what
is already used in Lensfun for same specs.

**Comment by maxmeyer** [comment]
Great. Thanks. :-)

**Comment by maxmeyer** [comment]
Are there any plans to release a new version soon?

**Comment by sarunasb** [comment]
On 2018-06-13 14:48, Dennis Günnewig wrote:
> Are there any plans to release a new version soon?

This, i.e. lensfun on github, is for calibration data upkeep only.

Lensfun itself is maintained at lensfun.sourceforge.net — that's where
you may ask...

**Comment by bronger** [comment]
Are there any open issues that need to be tagged “successful” due to this one having been merged?

**Comment by tomalakgeretkal** [comment]
The "short form" should still be:

> LEICA DG NOCTICRON 42.5mm f/1.2

rather than:

> LEICA DG NOCTICRON 42.5/F1.2

I'll PR it up.

**Comment by tomalakgeretkal** [comment]
I'm surprised to see calibration data with focal length of 43mm on a 42.5mm lens - what's happened there?

**Pull request merged**
