### PR TITLE
Added data for Sony FE 20mm F1.8 G lens for Sony E mount

### PR DESCRIPTION
**Pull request by GustavHaapalahti**
Added data for Sony FE 20mm F1.8 G lens for Sony E mount
Calibration images taken with a Sony A7 ii
Distortion calculation using Hugin.
Final step with calibrate.py script by Torsten Bronger

### CODE REVIEW

**Comment by tuxfanx** [comment]
I just looked at some pictures ([from the internet](https://www.dpreview.com/sample-galleries/)) in with your correction data in darktable. The correction for vignetting seemed too strong to me. Please double check it too. TCA and distortion seems to be ok. Do you know[ these calibration instructions](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/)?

**Comment by GustavHaapalahti** [comment]
Yes, I have read that article. I can upload the vignetting images I took if you want to look at them.
See http://gurre.eu/sony20mm-vignetting.zip

**Comment by tuxfanx** [comment]
Your vignetting images are ok. Don't you have the effect I described in your pictures? Maybe you would like to upload some suitable photos of you for comparison. You're right of course, we don't know enough about how the pictures were taken on DP.

**Comment by GustavHaapalahti** [comment]
When I look closely at some corrected images, then maybe there is a small
bit of over correction but on most images it looks fine. I uploaded a few
random examples at f1.8 f5.6 and f8 that are processed with darktable, both
without lens corrections and with it on.
http://gurre.eu/vignetting_examples

**Comment by tuxfanx** [comment]
it looks better in your pictures. I think the vignetting correction is ok - thank's

**Pull request merged**
