### PR TITLE
Add Samyang AF 35mm F1.8 (distortion)

### PR DESCRIPTION
**Pull request by bweigel**
Done using https://pixls.us/articles/create-lens-calibration-data-for-lensfun/

### CODE REVIEW

**Comment by tuxfanx** [comment]
The correction data for the lens are [already included](https://wilson.bronger.org/lensfun_coverage.html) in the db. Maybe you need to update your database.

**Comment by bweigel** [comment]
Thanks @tuxfanx , but I only see the lens profiles for the following lenses:
- [Samyang 35mm f/1.4 AS UMC](https://www.samyanglens.com/en/product/product-view.php?seq=287)
- [Samyang 35mm T1.5 Cine Lens](https://www.samyanglens.com/en/product/product-view.php?seq=315)

This PR however is for the [Samyang AF 35mm _F1.8_](https://www.samyanglens.com/en/product/product-view.php?seq=514). If I am not mistaken this lens is in fact NOT already included in the database.

**Comment by tuxfanx** [comment]
> Thanks @tuxfanx , but I only see the lens profiles for the following lenses:
> 
>     * [Samyang 35mm f/1.4 AS UMC](https://www.samyanglens.com/en/product/product-view.php?seq=287)
> 
>     * [Samyang 35mm T1.5 Cine Lens](https://www.samyanglens.com/en/product/product-view.php?seq=315)
> 
> 
> This PR however is for the [Samyang AF 35mm _F1.8_](https://www.samyanglens.com/en/product/product-view.php?seq=514). If I am not mistaken this lens is in fact NOT already included in the database.

Please check the [current database file on github](https://github.com/lensfun/lensfun/blob/master/data/db/mil-samyang.xml) again. Is the last entry in the file really not your lens?

**Comment by bweigel** [comment]
Ohh, yeah that is really my lens. I wonder why I did not see it at first. Sorry for the confusion. Thanks.

**Pull request closed without merging**
