### PR TITLE
Updated 24mm f1.4L II, 50mm 1.2L and 300mm 2.8L IS

### PR DESCRIPTION
**Pull request by PeterWem**
Updated the following lenses 24mm f1.4L II, 50mm 1.2L and 300mm 2.8L IS (x1.4 x1.4III and x2III)

### CODE REVIEW

**Comment by PeterWem** [comment]
Also fixes https://github.com/lensfun/lensfun/issues/1492

**Comment by EC1000** [comment]
I commented in https://github.com/lensfun/lensfun/issues/1492#issuecomment-981084196 but this PR is probably a better place, so I will paste it here. 

I think model names are missing "Canon" at the beggining (see issue #1504 and PR #1442).

```
<model>Canon RF 24-240mm F4-6.3 IS USM</model>
(...)
<model>Canon RF 50mm F1.8 STM</model>
```

instead of:

```
<model>RF 24-240mm F4-6.3 IS USM</model>
(...)
<model>RF 50mm F1.8 STM</model>
```

**Comment by PeterWem** [comment]
Will check what latest exiv2 calls the lenses and after that update with the right name.

**Comment by PeterWem** [comment]
With exiv2 0.27.5 I get 

Exif.Photo.LensModel RF85mm F2 MACRO IS STM
ExifCanon RF 85mm F1.2L USM

**Comment by PeterWem** [comment]
Got exiv2 0.27.5 with darkable today. RF 24-240 isn't read correctly anymore, so I will search and replace with Canon RF 24-240 etc...

**Comment by PeterWem** [comment]
All RF names now with Canon RF in front of them.
RF 16/2.8 and RF 24-105/4-7.1 added.
R3, M6 II, and M50 II added.

**Comment by Sturmflut** [comment]
The following open calibration uploads also have some form of data for lenses in this pull request:

Canon RF24-240mm F4-6.3 IS USM: #1524, #996, #992, #1065

Canon RF 24-105mm F4-7.1 IS STM: #1413

Canon RF 50mm F1.8 STM: #1480

Tamron E 17-28mm F2.8-2.8: #1466, #1302, #1402, #1303, #1079

Canon EF 50mm f/1.2L USM: #1326

I'll comb through them to see if someone can be added, then we can prepare to get the PR merged and close all of this.

**Comment by Sturmflut** [comment]
@PeterWem I spent the whole afternoon sorting it all out and comparing the data to other issues and pictures from calibration uploads. The good news: The majority of the data in this branch is good to go, and we got rid of at least twelve open issues in the process.

The not so good news: This pull request now simply has too many different changes, unnecessary merges with master and currently also conflicts with master since part of the data has already been merged.

Could you please create a fresh branch off of the current lensfun master branch and make three commits (one for Canon mirrorless, one for Tamron E 17-28mm F2.8-2.8 and one for Canon SLR) with sensible commit message? I made an example for the Canon mirrorless commit since it took me the whole afternoon to cross-reference it with other issues and calibration uploads:

```
Add new Canon mirrorless cameras and lenses

This adds the following changes:

* New: EOS M6 II, EOS M50 II, EOS R3 cameras

* New: Canon RF 16mm F2.8 STM lens (full data)

* New: Canon RF 14-35mm F4 L IS USM (full data)

* Fix: Canon RF 85mm F1.2L USM lens name
```

The Tamron E 17-28mm F2.8-2.8, EOS-1D C, Canon EF 300mm f/2.8L IS USM and Canon EF 300mm f/2.8L IS II USM are good to go as well.

There are open bugs for Canon RF lenses with duplicate Lens IDs, but that has to be figured out elsewhere and in cooperation with exiv2.


For reference and overview: The following items have already been handled elsewhere:

* Canon RF24-240mm F4-6.3 IS USM: Added via #1492, committed in lensfun/lensfun@de18df11cf5d8bb2d4317f7ba865b94263f1ec18

* Canon RF 50mm F1.8 STM: Added via #1492, committed in lensfun/lensfun@de18df11cf5d8bb2d4317f7ba865b94263f1ec18

* Canon RF 24-105 f/4-7.1 IS STM lens: I took the data from your branch and improved distortion correction at 24mm slightly using the pictures from calibration upload #1413. Committed in lensfun/lensfun@5e2fc515d431a298d66807822c243e1c38f6e079

* Canon RF85mm F2 MACRO IS STM: I completed your distortion data with TCA and vignetting from a seemingly incomplete calibration data upload (383c5e). Commited in lensfun/lensfun@99aeb2cb09d65c3a8c57a105f1af159d6218fa6b

**Comment by PeterWem** [comment]
It seems Torsten closed some old old old uploads of 24mm f/1.4 II and 300mm f/2.8L IS USM just a few minutes ago...The ones I uploaded were better I think.

**Comment by Sturmflut** [comment]
@PeterWem That's Torsten's bot. It closes uploads when issues are marked as successful/unsuccessful.

The data for the 300mm f/2.8L IS USM in this branch here should be good. That lens is not in the database yet.

But I've just noticed an error: I didn't remember seeing the 24mm f/1.4. Looks like you have a copy/paste error: The `<model>Canon EF 300mm f/2.8L IS II USM</model>` entry has calibrations for `focal="24.0"`. I guess that should actually be the 24mm f1.4L II and not the 300mm f/2.8L IS II USM?

**Comment by PeterWem** [comment]
slr-canon.xml updated https://github.com/lensfun/lensfun/pull/1603

Canon EF 300mm f/2.8L IS II USM is not a lens I have added, I hope. I have added first version of the lens Canon EF 300mm f/2.8L IS USM.

**Pull request closed without merging**
