### PR TITLE
Add calibration data for Canon RF 15-35mm F2.8L IS USM

### PR DESCRIPTION
**Pull request by cytrinox**
This add calibration data for the RF 15-35.

fixes https://github.com/lensfun/lensfun/issues/1699

### CODE REVIEW

**Comment by cytrinox** [comment]
@tuxfanx I've calibrated the lens last year and already sold it. Due to #1504 I've never submitted my calibrations.
If you need more images than available in #1699 please close this PR as I currently don't have access to this lens anymore.

**Comment by piratenpanda** [comment]
I really don't understand how you managed to get the same vignetting values for close and far. Is this indoor or outdoor? My values are always different

**Comment by cytrinox** [comment]
I followed https://pixls.us/articles/create-lens-calibration-data-for-lensfun/

For vignetting, I use a professional flat field from astro imaging: https://www.gerdneumann.net/deutsch/astrofotografie-parts-astrophotography/aurora-flatfield-panels/uebersicht-aurora-flatfield-panels-overview.html

**Comment by piratenpanda** [comment]
Nice, thanks

**Pull request merged**
